import Head from "next/head";
import Image from "next/image";
import { subscribeToPushNotifications } from "./_app";

export default function Home() {
  const enableNotifications = async () => {
    const res = await subscribeToPushNotifications();
    console.log(res);
  };
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div>
          <p>Get started by editing&nbsp;</p>
          <button onClick={() => enableNotifications()}> SUBSRIBE</button>
        </div>
      </main>
    </>
  );
}
